#!/usr/bin/env bash


MSdescr="Apply AO calibration"

MSextdescr="Load calibration to shared memory from filesystem
To be executed from loop rootdir"

source milk-script-std-config

# check and load cacaovars
source cacao-check-cacaovars
RequiredCommands=(milk)
RequiredPipes=()
RequiredFiles=()

MSarg+=( "calibname:string:calibration name" )


source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit 1
fi
set -u



calib="${inputMSargARRAY[0]}"
echo "Calibration : ${calib}"

#Directory name
BASEARCHDIR="../${CACAO_LOOPNAME}-calibs/"
ARCHDIR="${BASEARCHDIR}${calib}/"


echo "Loop ${CACAO_LOOPNUMBER}: Loading calibration from ${ARCHDIR}"

if [[ -d "${ARCHDIR}" ]]; then

#Shutdown processes
echo "runstop mvalC2dm-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
echo "confstop mvalC2dm-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo

echo "runstop mfilt-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
echo "confstop mfilt-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo

echo "runstop wfs2cmodeval-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
echo "confstop wfs2cmodeval-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo

echo "runstop acquWFS-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
echo "confstop acquWFS-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo

# Load CM to shared memory
milk-FITS2shm "${ARCHDIR}/CMmodesWFS/CMmodesWFS.fits" aol${CACAO_LOOPNUMBER}_CMmodesWFS
milk-FITS2shm "${ARCHDIR}/CMmodesDM/CMmodesDM.fits" aol${CACAO_LOOPNUMBER}_CMmodesDM

milk-FITS2shm "${ARCHDIR}/RMmodesWFS/zrespM-H.fits" aol${CACAO_LOOPNUMBER}_zrespM

milk-FITS2shm "${ARCHDIR}wfsref.fits" aol${CACAO_LOOPNUMBER}_wfsref
milk-FITS2shm "${ARCHDIR}wfsref.fits" aol${CACAO_LOOPNUMBER}_wfsrefc

milk-FITS2shm "${ARCHDIR}wfsmask.fits" aol${CACAO_LOOPNUMBER}_wfsmask

milk-FITS2shm "${ARCHDIR}dmmask.fits" aol${CACAO_LOOPNUMBER}_dmmask

#Startup processes
echo "confstart acquWFS-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "runstart acquWFS-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "confstart wfs2cmodeval-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "runstart wfs2cmodeval-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "confstart mfilt-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "runstart mfilt-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "confstart mvalC2dm-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo
sleep 1
echo "runstart mvalC2dm-${CACAO_LOOPNUMBER}" >> /milk/shm/${CACAO_LOOPNAME}_fpsCTRL.fifo

#zero the gain factors 
milk-shmim-zero "aol${CACAO_LOOPNUMBER}_mgainfact"

# record this calib as applied
echo $(pwd)/${ARCHDIR} > $MILK_SHM_DIR/aol${CACAO_LOOPNUMBER}_calib_source.txt

DATESTRING="$(date -u --iso-8601=seconds)"

echo ${DATESTRING} > $MILK_SHM_DIR/aol${CACAO_LOOPNUMBER}_calib_loaded.txt

echo "${DATESTRING} APPLY ${calib}" >> ${BASEARCHDIR}/aol${CACAO_LOOPNUMBER}_archive-log.txt


else
    echo "DIRECTORY DOES NOT EXIST"
fi
